### ISSUE TITLE
kube-resources-autosave-dumper liveness probe fails v0.9.9-rc.2 

### ISSUE THREAD

**Issue by joseppla** [kubernetes-incubator/kube-aws#1007] opened 2017-11-10 09:26 UTC
kubectl describe pod kube-resources-autosave-XXXXXXXX-XXXXX shows this output:

  7m		7m		1	kubelet, ip-X-X-X-X.ec2.internal	spec.containers{kube-resources-autosave-dumper}	Warning		Unhealthy		Liveness probe failed: /bin/bash: 1: cannot open 25*60*60: No such file
/bin/bash: 1: 1510305513: not found

**Comment by mumoshu** [comment] 2017-11-21 12:46
@joseppla Thanks for the report!
@redbaron @jollinshead Would you mind helping us locating the cause? Could upgrade to K8S 1.8 result in such a cryptic error?

**Comment by kevtaylor** [comment] 2017-11-21 13:20
@mumoshu it may be that the exec is being interpreted differently in 1.8 - I don't have 1.8 yet, but lokking at the error message looks like it has stripped the wildcard from the 25*60*60 - might be worth trying some quotes round the bash command?

**Comment by camilb** [comment] 2017-11-21 17:11
@mumoshu @kevtaylor The health check fails from the same reason described in #967 - hyperkube for 1.8 doesn't include bash anymore. So we have to write the health check for simple shell.

**Comment by camilb** [comment] 2017-11-23 10:57
@joseppla  Fixed in #1016

**Closed** 2017-11-24 03:03 UTC
Labels: help wanted
