### ISSUE TITLE
TLS handshake errors caused by Controller ELB running tcp healthchecks to 443

### ISSUE THREAD

**Issue by sasso** [kubernetes-incubator/kube-aws#295] opened 2017-02-02 17:31 UTC
We are seeing a lot of "TLS handshake error" on kube-apiserver and authproxy

![screenshot 2017-02-02 09 29 08](https://cloud.githubusercontent.com/assets/8398242/22560662/4512e5d0-e92a-11e6-9988-b436134d5d5d.png)

Anyone have any ideas why this is happening?

**Comment by redbaron** [comment] 2017-02-02 17:38
check from the client side, there should be  more informative error

**Comment by sasso** [comment] 2017-02-02 17:54
Client side works and I dont see any errors

**Comment by redbaron** [comment] 2017-02-02 17:56
there must be, these IPs belong to pods right? and something there failed to established connection

**Comment by sasso** [comment] 2017-02-02 18:00
huh, ok I think I can pin it to a service and ELB healthcheck. ty!

**Comment by sasso** [comment] 2017-02-02 19:38
![screenshot 2017-02-02 11 36 48](https://cloud.githubusercontent.com/assets/8398242/22565138/f36372c4-e93b-11e6-8bab-6927420e7d66.png)
![screenshot 2017-02-02 11 36 58](https://cloud.githubusercontent.com/assets/8398242/22565139/f37921fa-e93b-11e6-8b50-d8ecf28c832a.png)

This happens because we are doing TCP healthcheck on SSL listener

**Comment by whereisaaron** [comment] 2017-03-02 22:04
The apiserver requires a client certificate the ELB doesn't have, so the ELB can only do a TCP connect healthcheck, and that connect/disconnect triggers those errors in the logs. I get them too. It would be nice if there were someway to suppress them, or not log on a zero-data connect/disconnect.

**Comment by mumoshu** [comment] 2017-03-22 07:07
Thanks for the info @whereisaaron!
How about allowing unauthenticated http accesses to apiserver from ELB in a security group so that we can use http health checks instead of tcp checks?

**Comment by whereisaaron** [comment] 2017-03-23 02:25
Enabling any unauthenticated/anonymous access to the API makes be a bit uneasy @mumoshu !

It is possible for [failed client-cert requests to fall back to anonymous](https://kubernetes.io/docs/admin/authentication/#anonymous-requests), but I don't see that you can restrict those anonymous requests to just the ELB, so everyone with access to the API (from either side of the ELB) could make anonymous requests. These would map to the `system:unauthenticated` RBAC group and so access could be restricted by RBAC. But if you didn't have RBAC enabled, you'd have the whole cluster open for unauthenticated admin access.

So `--anonymous-auth=true` combined with RBAC authorization then you could enable successful HTTPS health checks by the ELB. That would also avoid these false-positive log entries.

I personally think these log entries are inappropriately conflating an empty TCP connect with real TLS negotiation errors. If the client doesn't send a single byte, I am not sure you could claim they are trying to negotiate anything. It is kind of like someone visits your website login page, but doesn't try to login at all, and then claiming that is a failed login. Seems like a specious stance. Fixing that would require a patch to the authproxy though.

**Comment by mumoshu** [comment] 2017-03-23 02:33
Thanks @whereisaaron!
How about `--insecure-port` then? I guess we can restrict accesses to the insecure port of a kube-apiserver with a security group so that only ELBs are allowed to access the insecure port.

**Comment by mumoshu** [comment] 2017-03-23 02:35
Ah, doing so would enable attackers to access an insecure port via cracked pods on controller nodes?

**Comment by jeremyd** [comment] 2017-04-04 20:17
I think we can close this.  This is just how TCP healthchecks work and there's no easy way to 'fix' it without sacrificing stability... cc @saso #bugcleaning

**Comment by redbaron** [comment] 2017-04-06 09:32
do we have any other ports opened by apiserver which can be checked by ELB?

**Comment by c-knowles** [comment] 2017-04-06 14:25
`/etc/kubernetes/manifests/kube-apiserver.yaml` says:
```yaml
- containerPort: 443
  hostPort: 443
  name: https
- containerPort: 8080
   hostPort: 8080
   name: local
```

8080 is used for the liveness probe too (`/healthz`).

**Comment by danielfm** [comment] 2017-04-06 14:27
AFAIK 8080 is the insecure port (bound to `127.0.0.1` by default), so I don't think using this port would work.

**Comment by mumoshu** [comment] 2017-04-28 06:29
This seems to have been fixed by SSL healthchecks. See #604 
@sasso @danielfm @c-knowles @redbaron @whereisaaron Could you confirm? Thanks!

**Closed by mumoshu** 2017-04-28 06:29 UTC

**Comment by c-knowles** [comment] 2018-05-21 11:15
Anyone seeing this again with a more recent version of kube-aws like 0.10.0?

**Comment by whereisaaron** [comment] 2018-05-22 05:33
Hi @c-knowles I think this fix was specific to the 'classic' ELB. Have you (like me) switched to the ELBv2 option that kube-aws offers now? That currently configures with a TCP healthcheck, which would have the same problem.

ELBv2 load balancers do support HTTP(S) health checks, even on TCP load balancers. So a similar fix may be possible for the ELBv2 configuration.

**Comment by c-knowles** [comment] 2018-05-22 07:27
@whereisaaron nope, we haven't swapped unless kube-aws changed the default. I'll investigate further, for now all the info I have it this seems to be re-occurring and not entirely sure why. My current guess is this is healthchecks we have inside the cloud init scripts/systemd unit and the nodes were unhealthy at the time (unrelated health issues).

**Comment by sonnysideup** [comment] 2018-07-20 16:14
I'm using kube-aws v0.10.2, a classic ELB for a single API endpoint and I'm seeing the TLS errors:

```
I0720 16:09:21.904678       1 logs.go:41] http: TLS handshake error from 10.30.12.238:34902: EOF
I0720 16:09:31.904127       1 logs.go:41] http: TLS handshake error from 10.30.12.238:34940: EOF
I0720 16:09:41.904106       1 logs.go:41] http: TLS handshake error from 10.30.12.238:34970: EOF
I0720 16:09:51.904188       1 logs.go:41] http: TLS handshake error from 10.30.12.238:35010: EOF
```

Maybe this is a regression?

**Comment by gun1x** [comment] 2019-07-23 20:21
When you dominate a market, you don't really care about small details like this. So what if the LB can send only TCP healthchecks? Just change the source code from apps so that it doesn't throw EOF errors when TCP healthchecks come in.

EASY!
