### ISSUE TITLE
kube-aws v0.9.5 "eni" for etcd 

### ISSUE THREAD

**Issue by stanleychow1110** [kubernetes-incubator/kube-aws#592] opened 2017-04-26 12:36 UTC
Hi, i am trying kube-aws 0.9.5 final to build a cluster, found etcd has two option in this version, eip & eni for "memberIdentityProvider", i tried to use "eni", it created "controller" & "etcd" servers, but then seems get stuck in creating something, cant create "worker" servers, but when i use "eip", the whole cluster can be built properly. Below is the CloudFormation log listed. Want to ask if my "eni" related settings is correct or not ?

CloudFormation log 
2017-04-26	Status	Type	Logical ID	Status reason
19:19:34 UTC+0800	CREATE_FAILED	AWS::CloudFormation::Stack	omo-dev-kubecluster-Controlplane-TYYAGSOEIS6D	The following resource(s) failed to create: [Controllers].

19:19:32 UTC+0800	CREATE_FAILED	AWS::AutoScaling::AutoScalingGroup	Controllers	Received 0 SUCCESS signal(s) out of 2. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement

19:19:31 UTC+0800	UPDATE_IN_PROGRESS	AWS::AutoScaling::AutoScalingGroup	Controllers	Failed to receive 2 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.

19:04:28 UTC+0800	CREATE_IN_PROGRESS	AWS::AutoScaling::AutoScalingGroup	Controllers	Resource creation Initiated

cluster.yaml
... 
  memberIdentityProvider: eni
  internalDomainName: xxx.yyy.com
  manageRecordSets: true
  hostedZone:
    id: xxxxxxxx
...

**Comment by mumoshu** [comment] 2017-04-26 12:42
Hi @stanleychow1110, thanks for trying kube-aws!
Could you inform me by answering two questions:

- What is the domain associated to the hosted zone specified by hostedZone.id? Is it same with the one represented in `internalDomainName`?
- Would you mind sharing me a gist containing the result of `journalctl` in one of failed controller nodes?

**Comment by stanleychow1110** [comment] 2017-04-27 12:45
Hi, Mumoshu,

1. yes, i use the same internal domain for hostedZone.id as "internalDomainName", this also the same domain for hostedZoneId (line35).
2. Please find one of the controller journalctl log, it keeps on prompting below. Seems to be cert. issue (Error:  x509: certificate is valid for *.ap-southeast-1.compute.amazonaws.com,...)
 
... ....
Apr 27 12:35:57 ip-10-132-23-34.ap-southeast-1.compute.internal systemd-machined[942]: New machine rkt-f66e38bd-1a03-4a3c-86b0-b75fd579520c.
Apr 27 12:35:57 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: Started Container rkt-f66e38bd-1a03-4a3c-86b0-b75fd579520c.
Apr 27 12:35:57 ip-10-132-23-34.ap-southeast-1.compute.internal decrypt-assets[27807]: [12556.575795] awscli[5]: decrypting assets
Apr 27 12:35:57 ip-10-132-23-34.ap-southeast-1.compute.internal decrypt-assets[27807]: [12556.576442] awscli[5]: decrypting /etc/kubernetes/ssl/apiserver-key.pem.enc
Apr 27 12:35:58 ip-10-132-23-34.ap-southeast-1.compute.internal decrypt-assets[27807]: [12556.917111] awscli[5]: decrypting /etc/kubernetes/ssl/apiserver.pem.enc
Apr 27 12:35:58 ip-10-132-23-34.ap-southeast-1.compute.internal decrypt-assets[27807]: [12557.246953] awscli[5]: decrypting /etc/kubernetes/ssl/ca.pem.enc
Apr 27 12:35:58 ip-10-132-23-34.ap-southeast-1.compute.internal decrypt-assets[27807]: [12557.577015] awscli[5]: decrypting /etc/kubernetes/ssl/etcd-client-key.pem.enc
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal decrypt-assets[27807]: [12557.911287] awscli[5]: decrypting /etc/kubernetes/ssl/etcd-client.pem.enc
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal decrypt-assets[27807]: [12558.245228] awscli[5]: done.
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: Stopped Container rkt-f66e38bd-1a03-4a3c-86b0-b75fd579520c.
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal systemd-machined[942]: Machine rkt-f66e38bd-1a03-4a3c-86b0-b75fd579520c terminated.
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal decrypt-assets[27807]: "f66e38bd-1a03-4a3c-86b0-b75fd579520c"
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal etcdctl[27959]: Error:  x509: certificate is valid for *.ap-southeast-1.compute.amazonaws.com, not etcd0.[xxx.yyy].com
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: flanneld.service: Control process exited, code=exited status=4
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: Failed to start flannel - Network fabric for containers (System Application Container).
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: Dependency failed for flannel docker export service - Network fabric for containers (System Application Container).
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: flannel-docker-opts.service: Job flannel-docker-opts.service/start failed with result 'dependency'.
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: flanneld.service: Unit entered failed state.
Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: flanneld.service: Failed with result 'exit-code'.
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: install-kube-system.service: Service hold-off time over, scheduling restart.
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: kube-node-taint-and-uncordon.service: Service hold-off time over, scheduling restart.
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: Stopped Taint this kubernetes node with its role and then uncordon it.
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: Stopped kubelet.service.
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: Starting kubelet.service...
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: Stopped install-kube-system.service.
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: Starting install-kube-system.service...
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemctl[27975]: activating
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: install-kube-system.service: Control process exited, code=exited status=3
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: Failed to start install-kube-system.service.
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: install-kube-system.service: Unit entered failed state.
Apr 27 12:36:01 ip-10-132-23-34.ap-southeast-1.compute.internal systemd[1]: install-kube-system.service: Failed with result 'exit-code'.
.... ...

**Comment by mumoshu** [comment] 2017-04-27 12:51
Thanks @stanleychow1110,

Hmm, that's odd! `etcd0.[xxx.yyy].com` should be included in the cert as long as etcd.internalDomainName is set and etcd.memberIdentityProvider is set to `eni`.
Would you mind sharing your cluster.yaml so that I can try to reproduce your setup?

**Comment by stanleychow1110** [comment] 2017-04-27 16:34
Hi, Mumoshu,

Pls find the attach zip for the cluster.yaml, pls note that i changed the following for privacy 

externalDNSName
hostedZoneId
keyName
etcd.internalDomainName
etcd.hostedZone.id
[cluster.yaml.zip](https://github.com/kubernetes-incubator/kube-aws/files/962237/cluster.yaml.zip)

**Comment by mumoshu** [comment] 2017-05-17 00:31
@stanleychow1110 Sorry for the silence and thanks for the additional info 👍 

I've been thinking about this for a while but no insight so far.

The error:

> Apr 27 12:35:59 ip-10-132-23-34.ap-southeast-1.compute.internal etcdctl[27959]: Error: x509: certificate is valid for *.ap-southeast-1.compute.amazonaws.com, not etcd0.[xxx.yyy].com

shouldn't really occur as `etcd.pem` must include `*.[xxx.yyy].com` in `Subject Alternative Name`.
Go code constructing `Subject Alternative Name`s for etcd nodes when `memberIdentityProvider: eni` is enabled can be found in:
* https://github.com/kubernetes-incubator/kube-aws/blob/5f60607620c2c55c5f96372c5b596eae6207e406/core/controlplane/config/tls_config.go#L177
* https://github.com/kubernetes-incubator/kube-aws/blob/5f60607620c2c55c5f96372c5b596eae6207e406/model/derived/etcd_cluster.go#L38-L45

Could you run `openssl x509 -in etcd.pem -noout -text` on the `etcd.pem` in your local machine and also on one in the problematic node(=worker), to see actual `Subject Alternative Name`s provided there?

**Comment by VinceMD** [comment] 2017-07-18 08:46
I'm having the same exact issue. My etcd settings:

` memberIdentityProvider: eni
  internalDomainName: "etcd-np-kube-001.assn.wrkntest.MYCOMPANY-aws.local"
  manageRecordSets: true
  hostedZone:
    id: "MYZONEID"`

I tried to run the openssl command on etcd.pem, but not sure the syntax:
` openssl x509 -in etcd.pem -noout -text etcd.pem `
unknown option etcd.pem

I can't run that on workers , as suggested, since it does not get to this stage (it fails at creating the Controller).

**Comment by mumoshu** [comment] 2017-07-18 09:10
@VinceMD Could you confirm that you've started with the new cluster? For example, updating cluster.yaml with memberIdentityProvider after `kube-aws render credentials` won't work!

**Comment by VinceMD** [comment] 2017-07-18 09:21
I think you are right. Worse, I probably needed to regenerate the certificate as I added the internalDomain later on. Let me run double check I can go pass this stage and we can probably close this issue.

**Comment by mumoshu** [comment] 2017-07-18 11:31
@VinceMD Thanks, I'm looking forward to your report 👍

**Comment by mumoshu** [comment] 2017-07-18 11:35
@stanleychow1110 Sorry for the long silence without any check-in but now,
I realized that you by any chance had to re-run `kube-aws render credentials` after updating memberIdentityProvider in cluster.yaml from eip to eni.

**Comment by VinceMD** [comment] 2017-07-19 04:48
No issue for me anymore after regenerating certificates. IMHO this is not an issue, just user error / doc

**Comment by whereisaaron** [comment] 2017-12-17 19:49
@mumoshu if `internalDomainName` were a list then they `render credentials` certificates could support both the '.internal' and '.com' domains. Then the default certificates would work with either the `eni` or `eip` setting, without regeneration?

**Closed** 2019-06-21 09:24 UTC
Labels: awaiting reply, lifecycle/rotten
