### ISSUE TITLE
v0.9.7 - kuberbetes 1.6.3 - IOPS not supported for gp2 volumes

### ISSUE THREAD

**Issue by Ruwan-Ranganath** [kubernetes-incubator/kube-aws#1401] opened 2018-07-09 14:49 UTC
When running 

> kube-aws up --s3-uri=s3://foo-bar

Error: Error validating cluster: failed to validate node pool #0: create volume dry-run request failed: InvalidParameterCombination: The parameter iops is not supported for gp2 volumes.
	status code: 400, request id: 7b169590-73a5-4e4c-bbdc-dabf1b8c553a

**Comment by c-knowles** [comment] 2018-07-09 14:54
This is a duplicate of https://github.com/kubernetes-incubator/kube-aws/issues/1170 which is is fixed in v0.9.10.

**Closed by c-knowles** 2018-07-09 14:54 UTC
