### ISSUE TITLE
ImageGCFailed

### ISSUE THREAD

**Issue by cdenneen** [kubernetes-incubator/kube-aws#690] opened 2017-06-01 22:01 UTC
4 pods pending with no change:

```
kubectl --kubeconfig=kubeconfig get pods --all-namespaces
NAMESPACE     NAME                                                READY     STATUS    RESTARTS   AGE
kube-system   heapster-v1.3.0-268032834-s810c                     0/2       Pending   0          35m
kube-system   kube-apiserver-ip-10-0-0-39.ec2.internal            1/1       Running   0          34m
kube-system   kube-controller-manager-ip-10-0-0-39.ec2.internal   1/1       Running   0          34m
kube-system   kube-dns-1455470676-gwfj3                           0/3       Pending   0          35m
kube-system   kube-dns-autoscaler-1464605019-8wsn9                0/1       Pending   0          35m
kube-system   kube-proxy-ip-10-0-0-39.ec2.internal                1/1       Running   0          35m
kube-system   kube-scheduler-ip-10-0-0-39.ec2.internal            1/1       Running   0          34m
kube-system   kubernetes-dashboard-v1.5.1-jjj8j                   0/1       Pending   0          35m
```

```
kubectl --kubeconfig=kubeconfig get events
LASTSEEN   FIRSTSEEN   COUNT     NAME                        KIND      SUBOBJECT   TYPE      REASON                    SOURCE                                  MESSAGE
37m        37m         1         ip-10-0-0-39.ec2.internal   Node                  Normal    Starting                  kubelet, ip-10-0-0-39.ec2.internal      Starting kubelet.
37m        37m         1         ip-10-0-0-39.ec2.internal   Node                  Warning   ImageGCFailed             kubelet, ip-10-0-0-39.ec2.internal      unable to find data for container /
36m        37m         27        ip-10-0-0-39.ec2.internal   Node                  Normal    NodeHasSufficientDisk     kubelet, ip-10-0-0-39.ec2.internal      Node ip-10-0-0-39.ec2.internal status is now: NodeHasSufficientDisk
36m        37m         27        ip-10-0-0-39.ec2.internal   Node                  Normal    NodeHasSufficientMemory   kubelet, ip-10-0-0-39.ec2.internal      Node ip-10-0-0-39.ec2.internal status is now: NodeHasSufficientMemory
36m        37m         27        ip-10-0-0-39.ec2.internal   Node                  Normal    NodeHasNoDiskPressure     kubelet, ip-10-0-0-39.ec2.internal      Node ip-10-0-0-39.ec2.internal status is now: NodeHasNoDiskPressure
36m        36m         1         ip-10-0-0-39.ec2.internal   Node                  Normal    Starting                  kube-proxy, ip-10-0-0-39.ec2.internal   Starting kube-proxy.
36m        36m         1         ip-10-0-0-39.ec2.internal   Node                  Normal    RegisteredNode            controllermanager                       Node ip-10-0-0-39.ec2.internal event: Registered Node ip-10-0-0-39.ec2.internal in NodeController
```

**Comment by redbaron** [comment] 2017-06-02 10:08
I wouldn't worry about GCFailed warning yet. Can you provide `kubectl -n kube-system describe  kube-dns-1455470676-gwfj3` output?

**Comment by cdenneen** [comment] 2017-06-02 13:06
@redbaron 
It's pending so I don't think that will work:

```
 ~/src/base_cluster2  kubectl --kubeconfig=kubeconfig get pods -n kube-system
NAME                                                READY     STATUS    RESTARTS   AGE
heapster-v1.3.0-268032834-s810c                     0/2       Pending   0          15h
kube-apiserver-ip-10-0-0-39.ec2.internal            1/1       Running   0          15h
kube-controller-manager-ip-10-0-0-39.ec2.internal   1/1       Running   0          15h
kube-dns-1455470676-gwfj3                           0/3       Pending   0          15h
kube-dns-autoscaler-1464605019-8wsn9                0/1       Pending   0          15h
kube-proxy-ip-10-0-0-39.ec2.internal                1/1       Running   0          15h
kube-scheduler-ip-10-0-0-39.ec2.internal            1/1       Running   0          15h
kubernetes-dashboard-v1.5.1-jjj8j                   0/1       Pending   0          15h
 ~/src/base_cluster2  kubectl --kubeconfig=kubeconfig -n kube-system describe kube-dns-1455470676-gwfj3
the server doesn't have a resource type "kube-dns-1455470676-gwfj3"
```

**Comment by redbaron** [comment] 2017-06-02 20:40
oops, wrong syntax from my side:

```
kubectl -n kube-system describe pod kube-dns-1455470676-gwfj3
```

**Comment by cdenneen** [comment] 2017-06-05 18:39
@redbaron Sorry for the delay... here is the info requested:

```
kubectl --kubeconfig=kubeconfig -n kube-system describe pod kube-dns-1455470676-gwfj3
Name:		kube-dns-1455470676-gwfj3
Namespace:	kube-system
Node:		/
Labels:		k8s-app=kube-dns
		pod-template-hash=1455470676
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kube-dns-1455470676","uid":"920b5616-4710-11e7-933b-067d3005...
		scheduler.alpha.kubernetes.io/critical-pod=
Status:		Pending
IP:
Controllers:	ReplicaSet/kube-dns-1455470676
Containers:
  kubedns:
    Image:	gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.1
    Ports:	10053/UDP, 10053/TCP, 10055/TCP
    Args:
      --domain=cluster.local.
      --dns-port=10053
      --config-map=kube-dns
      --v=2
    Limits:
      memory:	170Mi
    Requests:
      cpu:	100m
      memory:	70Mi
    Liveness:	http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:	http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment:
      PROMETHEUS_PORT:	10055
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-g94kr (ro)
  dnsmasq:
    Image:	gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.1
    Ports:	53/UDP, 53/TCP
    Args:
      -v=2
      -logtostderr
      -restartDnsmasq=true
      --
      -k
      --cache-size=1000
      --log-facility=-
      --server=/cluster.local/127.0.0.1#10053
      --server=/in-addr.arpa/127.0.0.1#10053
      --server=/ip6.arpa/127.0.0.1#10053
    Requests:
      cpu:		150m
      memory:		20Mi
    Liveness:		http-get http://:10054/healthcheck/dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-g94kr (ro)
  sidecar:
    Image:	gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.1
    Port:	10054/TCP
    Args:
      --v=2
      --logtostderr
      --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,A
      --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,A
    Requests:
      cpu:		10m
      memory:		20Mi
    Liveness:		http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-g94kr (ro)
Conditions:
  Type		Status
  PodScheduled 	False
Volumes:
  default-token-g94kr:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-g94kr
    Optional:	false
QoS Class:	Burstable
Node-Selectors:	<none>
Tolerations:	CriticalAddonsOnly=:Exists
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----			-------------	--------	------			-------
  3d		2s		19104	default-scheduler			Warning		FailedScheduling	No nodes are available that match all of the following predicates:: PodToleratesNodeTaints (1).
```

**Comment by PuKoren** [comment] 2017-06-05 19:47
I have the exact same symptoms when I tried a fresh deployment today, it appears to be coming from etcd TLS failure (considered as unhealthy by the controllers)

Can you put the output of the command `kubectl get cs`?

**Comment by cdenneen** [comment] 2017-06-05 19:49
```
kubectl --kubeconfig=kubeconfig get cs
NAME                 STATUS      MESSAGE                                                                                                 ERROR
scheduler            Healthy     ok
controller-manager   Healthy     ok
etcd-1               Unhealthy   Get https://ec2-34-225-74-112.compute-1.amazonaws.com:2379/health: remote error: tls: bad certificate
etcd-2               Unhealthy   Get https://ec2-52-201-4-87.compute-1.amazonaws.com:2379/health: remote error: tls: bad certificate
etcd-0               Unhealthy   Get https://ec2-34-202-174-68.compute-1.amazonaws.com:2379/health: remote error: tls: bad certificate
```

**Comment by PuKoren** [comment] 2017-06-05 20:05
I think etcd fails so controllers are not aware of workers (can confirm that with `kubectl get nodes`, you will see only your controller nodes), so kube can't schedule pods on worker nodes (heapster, dashboard, kube-dns etc.)

I'm still digging into the issue to try to find a workaround (need it for a deployment tomorrow), will keep this thread updated if I find anything

**Comment by cdenneen** [comment] 2017-06-05 20:07
```
kubectl --kubeconfig=kubeconfig get nodes
NAME                        STATUS    AGE       VERSION
ip-10-0-0-39.ec2.internal   Ready     3d        v1.6.2+coreos.0
```

**Comment by cdenneen** [comment] 2017-06-05 20:21
the nodes are there... and should be using the certs generated with render... 

<img width="751" alt="screen shot 2017-06-05 at 4 20 57 pm" src="https://cloud.githubusercontent.com/assets/720097/26801475/00bd9bae-4a0b-11e7-9681-72cedb7c8a4f.png">

**Comment by PuKoren** [comment] 2017-06-05 20:23
They are, but it seems that the controller is rejecting the ones used by ETCD as he don't know the certificate authority. Still digging into the issue

**Comment by PuKoren** [comment] 2017-06-05 21:00
More debug info:

Classic curl on ETCD:
```
curl https://ec2-54-77-39-250.eu-west-1.compute.amazonaws.com:2379/health
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html
```

Curl with --insecure on ETCD
```
curl https://ec2-54-77-39-250.eu-west-1.compute.amazonaws.com:2379/health --insecure
curl: (35) error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
```

**Comment by cdenneen** [comment] 2017-06-05 21:03
Does that normally work or do you have to pass the ca certificate to curl to use for that request?

**Comment by PuKoren** [comment] 2017-06-05 21:37
Yes it is supposed to work you can try it out on this sample self-signed ssl website: https://self-signed.badssl.com/

**Comment by cdenneen** [comment] 2017-06-06 14:55
@PuKoren yes I just meant without the cacert and capath parameters:

```
core@ip-10-0-0-39 /etc/kubernetes/ssl $ curl -v https://ec2-52-201-4-87.compute-1.amazonaws.com:2379/health
*   Trying 10.0.0.68...
* TCP_NODELAY set
* Connected to ec2-52-201-4-87.compute-1.amazonaws.com (10.0.0.68) port 2379 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
core@ip-10-0-0-39 /etc/kubernetes/ssl $ curl -v --cacert /etc/kubernetes/ssl/ca.pem --capath /etc/kubernetes/ssl https://ec2-52-201-4-87.compute-1.amazonaws.com:2379/health
*   Trying 10.0.0.68...
* TCP_NODELAY set
* Connected to ec2-52-201-4-87.compute-1.amazonaws.com (10.0.0.68) port 2379 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* error setting certificate verify locations:
  CAfile: /etc/kubernetes/ssl/ca.pem
  CApath: /etc/kubernetes/ssl
* Closing connection 0
curl: (77) error setting certificate verify locations:
  CAfile: /etc/kubernetes
```

**Comment by ankon** [comment] 2017-06-19 15:55
~~~~
curl: (77) error setting certificate verify locations:
  CAfile: /etc/kubernetes
~~~~

This seems to be caused by missing permissions. 

I seem to have the same TLS issue as reported by `kubectl get cs`, and this is the output with `sudo`:
~~~~
$ sudo curl -v --cacert /etc/kubernetes/ssl/ca.pem --capath /etc/kubernetes/ssl  https://ip-10-0-0-160.eu-west-1.compute.internal:2379/health
*   Trying 10.0.0.160...
* TCP_NODELAY set
* Connected to ip-10-0-0-160.eu-west-1.compute.internal (10.0.0.160) port 2379 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/kubernetes/ssl/ca.pem
  CApath: /etc/kubernetes/ssl
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS alert, Server hello (2):
* error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
* Curl_http_done: called premature == 1
* Closing connection 0
curl: (35) error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate
~~~~

**Comment by adimarco** [comment] 2017-09-19 17:34
Did anyone find a workaround for this?  The practical upshot is that clusters launched by kube-aws per the docs are completely unusable right now because nothing works without etcd.

**Comment by mumoshu** [comment] 2017-09-19 20:53
@adimarco Hi!
Excuse me but I don't understand your exact issue because your cluster should work if you really followed the doc.
Could you share your kube-aws version and cluster.yaml so that we can investigate what's wrong?

**Comment by adimarco** [comment] 2017-09-20 18:29
Hey @mumoshu - I don't know what I did the first time around, but after destroying it and starting from scratch again everything works as expected.  I must have fat-fingered some piece of config.  My etcd nodes were coming up unhealthy and throwing the "remote error: tls: bad certificate" error I saw above here, but all is now well.  Thanks for the reply.

**Closed** 2019-06-20 21:12 UTC
Labels: lifecycle/rotten
