### ISSUE TITLE
latest v0.9.3-rc.5 version is failing 

### ISSUE THREAD

**Issue by iam404** [kubernetes-incubator/kube-aws#257] opened 2017-01-17 02:59 UTC
```
core@ip-10-0-101-168 ~ $ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─40-flannel.conf
   Active: failed (Result: exit-code) since Tue 2017-01-17 02:58:05 UTC; 11s ago
     Docs: http://docs.docker.com
  Process: 3601 ExecStartPre=/usr/bin/systemctl is-active flanneld.service (code=exited, status=3)

Jan 17 02:58:05 ip-10-0-101-168 systemd[1]: Starting Docker Application Container Engine...
Jan 17 02:58:05 ip-10-0-101-168 systemctl[3601]: activating
Jan 17 02:58:05 ip-10-0-101-168 systemd[1]: docker.service: Control process exited, code=exited status=3
Jan 17 02:58:05 ip-10-0-101-168 systemd[1]: Failed to start Docker Application Container Engine.
Jan 17 02:58:05 ip-10-0-101-168 systemd[1]: docker.service: Unit entered failed state.
Jan 17 02:58:05 ip-10-0-101-168 systemd[1]: docker.service: Failed with result 'exit-code'.
```

**Comment by mumoshu** [comment] 2017-01-17 03:13
Hi @iam404, thanks for trying kube-aws!
As it is working for me without problem(s), it might be related to one of more customization(s) you've made to `cluster.yaml`, `stack-template.json`, `userdata/cloud-config-*`, etc.
Would you mind sharing us more context to further investigate your issue?

**Comment by mumoshu** [comment] 2017-01-17 03:39
Also, have you successfully launch your cluster with kube-aws older than v0.9.3-rc.5?

**Comment by iam404** [comment] 2017-01-18 06:16
@mumoshu Yes ! v0.9.1 is working fine.

**Comment by iam404** [comment] 2017-01-18 06:18
@mumoshu Also we do not have any custom changes to any other files. 
Only `cluster.yaml` and that is working with v0.9.1.

**Comment by pyralis** [comment] 2017-01-25 18:18
I'm having a similar problem. When I run `systemctl status flanneld.service`    it appears to fail on 

`ExecStartPre=/usr/bin/rkt rm --uuid-file=/var/lib/coreos/flannel-wrapper.uuid` (sorry I don't have the full output right now)

 When I ran with all the defaults for cluster.yaml I did not encounter this error. I'm likely to run again in a moment. If I run into the same issue I will provide more of the output.

**Comment by pyralis** [comment] 2017-01-25 18:59
console on login

`Update Strategy: No Reboots
Failed Units: 2
  docker.service
  flannel-docker-opts.service`

 after `systemctl status docker.service`

```
  ● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─40-flannel.conf
   Active: failed (Result: exit-code) since Wed 2017-01-25 18:37:11 UTC; 52s ago
     Docs: http://docs.docker.com
  Process: 2258 ExecStartPre=/usr/bin/systemctl is-active flanneld.service (code=exited, status=3)

Jan 25 18:37:11 ip-10-126-15-205.ec2.internal systemctl[2258]: activating
Jan 25 18:37:11 ip-10-126-15-205.ec2.internal systemd[1]: Starting Docker Application Container Engine...
Jan 25 18:37:11 ip-10-126-15-205.ec2.internal systemd[1]: docker.service: Control process exited, code=exited status=3
Jan 25 18:37:11 ip-10-126-15-205.ec2.internal systemd[1]: Failed to start Docker Application Container Engine.
Jan 25 18:37:11 ip-10-126-15-205.ec2.internal systemd[1]: docker.service: Unit entered failed state.
Jan 25 18:37:11 ip-10-126-15-205.ec2.internal systemd[1]: docker.service: Failed with result 'exit-code'.
```


then `systemctl status flanneld.service`

```
~ # systemctl status flanneld.service
● flanneld.service - flannel - Network fabric for containers (System Application Container)
   Loaded: loaded (/usr/lib/systemd/system/flanneld.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/flanneld.service.d
           └─10-etcd.conf
   Active: activating (start-pre) since Wed 2017-01-25 18:38:42 UTC; 29s ago
     Docs: https://github.com/coreos/flannel
  Process: 2868 ExecStartPre=/usr/bin/rkt rm --uuid-file=/var/lib/coreos/flannel-wrapper.uuid (code=exited, status=254)
  Process: 2864 ExecStartPre=/usr/bin/mkdir --parents /var/lib/coreos /run/flannel (code=exited, status=0/SUCCESS)
  Process: 2855 ExecStartPre=/sbin/modprobe ip_tables (code=exited, status=0/SUCCESS)
Cntrl PID: 2876 (decrypt-tls-ass)
    Tasks: 8
   Memory: 7.9M
      CPU: 71ms
   CGroup: /system.slice/flanneld.service
           └─control
             ├─2876 /bin/bash -e /opt/bin/decrypt-tls-assets
             └─2879 rkt run --volume=ssl,kind=host,source=/etc/kubernetes/ssl,readOnly=false --mount=volume=ssl,target=/etc/kubernetes/ssl --uuid-f

Jan 25 18:38:42 ip-10-126-15-205.ec2.internal systemd[1]: Stopped flannel - Network fabric for containers (System Application Container).
Jan 25 18:38:42 ip-10-126-15-205.ec2.internal systemd[1]: Starting flannel - Network fabric for containers (System Application Container)...
Jan 25 18:38:42 ip-10-126-15-205.ec2.internal rkt[2868]: rm: unable to resolve UUID from file: open /var/lib/coreos/flannel-wrapper.uuid: no such f
Jan 25 18:38:42 ip-10-126-15-205.ec2.internal rkt[2868]: rm: failed to remove one or more pods
```

When the cluster is configured it is placed into a new subnet that is does not route out to the internet. I'm just now seeing the config routeTableID in cluster.yaml  I'm going to try and set that to my internet gateway from the start and see if that has an impact.

**Comment by mumoshu** [comment] 2017-01-27 06:56
@iam404 Hmmm, that's odd.
Could you provide us an example output of `journalctl -u docker.service`?

**Comment by rajivm** [comment] 2017-01-27 08:28
I'm getting this same error as well, specifically on the controller nodes after creating a brand-new cluster in a new VPC. I have attempted it twice with the same result. 

I have previously, using the same version of kube-aws (rc5), been able to create a cluster that worked fine, but I had hardcoded it to use an AMI of version 1185.3.0 of CoreOS. This time I let it use the latest stable (CoreOS-stable-1235.6.0) and it failed to come up.

```
Container Linux by CoreOS stable (1235.6.0)
Update Strategy: No Reboots
Failed Units: 1
  docker.service
```


systemctl status docker.service
```docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─40-flannel.conf
   Active: failed (Result: exit-code) since Fri 2017-01-27 08:26:31 UTC; 7s ago
     Docs: http://docs.docker.com
  Process: 6732 ExecStartPre=/usr/bin/systemctl is-active flanneld.service (code=exited, status=3)

Jan 27 08:26:31 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
Jan 27 08:26:31 ip-10-0-0-227.us-west-2.compute.internal systemctl[6732]: activating
Jan 27 08:26:31 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Control process exited, code=exited status=3
Jan 27 08:26:31 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
Jan 27 08:26:31 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Unit entered failed state.
Jan 27 08:26:31 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.```


journalctl -u docker.service
This keeps repeating in the log:
```
Jan 27 08:10:58 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
Jan 27 08:10:58 ip-10-0-0-227.us-west-2.compute.internal systemctl[1392]: activating
Jan 27 08:10:58 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Control process exited, code=exited status=3
Jan 27 08:10:58 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
Jan 27 08:10:58 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Unit entered failed state.
Jan 27 08:10:58 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 27 08:11:05 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
Jan 27 08:11:05 ip-10-0-0-227.us-west-2.compute.internal systemctl[1656]: activating
Jan 27 08:11:05 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Control process exited, code=exited status=3
Jan 27 08:11:05 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
Jan 27 08:11:05 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Unit entered failed state.
Jan 27 08:11:05 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 27 08:11:32 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
Jan 27 08:11:32 ip-10-0-0-227.us-west-2.compute.internal systemctl[2199]: activating
Jan 27 08:11:32 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Control process exited, code=exited status=3
Jan 27 08:11:32 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
Jan 27 08:11:32 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Unit entered failed state.
Jan 27 08:11:32 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 27 08:11:46 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
Jan 27 08:11:46 ip-10-0-0-227.us-west-2.compute.internal systemctl[2482]: activating
Jan 27 08:11:46 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Control process exited, code=exited status=3
Jan 27 08:11:46 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
Jan 27 08:11:46 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Unit entered failed state.
Jan 27 08:11:46 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 27 08:11:59 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...
Jan 27 08:11:59 ip-10-0-0-227.us-west-2.compute.internal systemctl[2750]: activating
Jan 27 08:11:59 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Control process exited, code=exited status=3
Jan 27 08:11:59 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Failed to start Docker Application Container Engine.
Jan 27 08:11:59 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Unit entered failed state.
Jan 27 08:11:59 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 27 08:12:13 ip-10-0-0-227.us-west-2.compute.internal systemd[1]: Starting Docker Application Container Engine...```

**Comment by rajivm** [comment] 2017-01-27 23:55
`CoreOS-stable-1185.5.0` is also failing for me now -- I have one cluster that works fine with it (single controller), and another that has the above error (multi-AZ, multi-controller).

**Comment by drock** [comment] 2017-01-31 07:55
I have run into this problem as well.  I have tracked my instance down to attempting to upgrade from 0.9.1 to 0.9.3.rc-5.  When I originally ran kube-aws up on my cluster, my single etcd node got the IP address 10.0.1.5.  However, after upgrading to 0.9.3.rc-5 the etcd instance ip that is generated from the config ends up being 10.0.1.4 and that is what is put into cloud-config-controller.

Thus the controller is unable to reach etcd.  This can be seen by running journalctl -t etcdctl

Moving back down to 0.9.1 fixes the issue for me.

I suspect the issue is related to https://github.com/coreos/kube-aws/blob/v0.9.3-rc.5/config/config.go#L496 which is present in 0.9.3 but not 0.9.1.

**Comment by mumoshu** [comment] 2017-02-01 08:02
Hi all!
Anyways, please don't use `kube-aws update` among different kube-aws.
It is not intended to be supported(we aren't sure how it could be supported in the first place. Is it realistic to test every possible combination of an old and a new versions of kube-aws?).
`kube-aws up` an another cluster and migrate to it like I've described in https://github.com/coreos/kube-aws/issues/266#issuecomment-275571871 is a procedure of my recommendation.

**Comment by mumoshu** [comment] 2017-02-01 08:03
Pull request(s) are welcomed to add the doc not for updating but for up"grading" kube-aws cluster(s) :bow:

**Comment by mumoshu** [comment] 2017-02-01 08:07
Hi @rajivm, thanks for the info!
I'm not yet sure what's causing your problem.
Could you share me an example `cluster.yaml` for me to reproduce it?

**Comment by mumoshu** [comment] 2017-02-01 08:09
Hi @drock, I'm not really sure what was originally causing your problem but we've recently moved out of pre-calculated ips for etcd nodes via #226 which is included in v0.9.4-rc.1 released today.
Would you mind trying v0.9.4-rc.1?

**Comment by mumoshu** [comment] 2017-02-01 08:14
Hi @pyralis, thanks for the feedback!
Regarding your comment https://github.com/coreos/kube-aws/issues/257#issuecomment-275199757, I've updated comments in `cluster.yaml` to make it clearer that its users' responsibility to configure the route table if `routeTableId` is specified i.e.:

* if you'd like your subnets to be private, the route table must have a route to NAT or
* for public subnets it indeed must have a route to an internet gateway

**Comment by drock** [comment] 2017-02-01 20:08
@mumoshu my problem is related to upgrading from 0.9.1 to 0.9.3.  The pre-calculated IP for the etcd node when I deployed with 0.9.1 was 10.0.1.5 and that is what was assigned to it from the generated CF template.  With 0.9.3 however, the pre-calculated IP ended up being 10.0.1.4.  That is what ended up getting set as the ETCDENDPOINT in the worker and controller cloud-configs.  Since kube-aws doesn't touch etcd instances on update, the etcd instance stays at 10.0.1.5 however and thus the kublets try to talk to the wrong address.

> Would you mind trying v0.9.4-rc.1?

Can I safely use that to "up" a new cluster into the existing VPC of the cluster I launched with 0.9.1?  All of my apps in that cluster need to communicate with databases within the VPC.  Moving all of those databases to a new VPC would be a pain.

**Comment by mumoshu** [comment] 2017-02-06 08:13
Thanks @drock, sorry about that but `kube-aws update` is not intended to be used for "upgrading" kube-aws.

> Can I safely use that to "up" a new cluster into the existing VPC of the cluster I launched with 0.9.1? 

To be honest I can't guarantee anything but anyways it is intended to support that use-case.
Former kube-aws versions assumed very first IP addresses of the vpc/subnet CIDR range is reserved for etcd nodes hence theoretically it was impossible to deploy multiple kube-aws clusters into one vpc.
Since v0.9.4-rc.1, etcd IPs are assigned dynamically and therefore there's no such restriction.

**Comment by redbaron** [comment] 2017-02-06 15:15
> sorry about tha,  but kube-aws update is not intended to be used for "upgrading" kube-aws.
I didn't find mentions of it in the doc. What can be done to support rolling upgrades? Is it a planned goal at all?

**Comment by mumoshu** [comment] 2017-02-09 08:09
@redbaron Not planned yet i.e. it is at the priority lower than other features, improvements, etc.

**Comment by redbaron** [comment] 2017-02-09 08:19
@mumoshu I understand it, but what would be the best format to discuss missing features so that we can have a clear plan and interested people can contribute towards it?

**Comment by mumoshu** [comment] 2017-02-09 08:55
@redbaron How about discuss in github issues and then someone wants to get involved at most send pull requests to [our roadmap](https://github.com/coreos/kube-aws/blob/master/ROADMAP.md), so that anyone can just contribute by implementing features noted in our roadmap?

**Comment by danehans** [comment] 2017-03-14 21:16
I am having a similar issue using matchbox to deploy a coreos k8s cluster.

https://github.com/coreos/flannel/issues/640

**Comment by mumoshu** [comment] 2017-03-22 07:26
Thanks for the info @danehans!
JFYI, errors seem above are very general; In other words, you see those when there's misconfiguration(s) in flannel for various reasons, regardless of what your provisioning tool is.

**Comment by mumoshu** [comment] 2017-03-22 07:27
Closing this as the original issue is clarified and the follow up issue is at #311

**Closed by mumoshu** 2017-03-22 07:27 UTC
Labels: need more info
