### ISSUE TITLE
Bug: Output says default endpoint managed by user

### ISSUE THREAD

**Issue by c-knowles** [kubernetes-incubator/kube-aws#485] opened 2017-04-03 06:01 UTC
On latest master, set `externalDNSName` and `hostedZoneId` to something and `createRecordSet: true`

~~Output of `render stack` says:~~
Output of `validate` says:

```
WARN: the worker node pool "nodepool1" is associated to a k8s API endpoint behind the DNS name "k8s-OBFUSCATED" managed by YOU!
```

However, I think this is not true - the endpoint it managed by kube-aws.

**Comment by mumoshu** [comment] 2017-04-03 07:16
@c-knowles Thanks for the report 👍 
However I can't reproduce it - could you verify that `hostedZoneId` is also specified?

**Comment by c-knowles** [comment] 2017-04-03 08:29
Yes it, updated above.

**Comment by mumoshu** [comment] 2017-04-03 13:15
@c-knowles Hmm, that's odd... Would you mind sharing me an example cluster.yaml to reproduce the issue?

**Comment by c-knowles** [comment] 2017-04-03 15:30
Yep sure. It's an entirely new cluster I've been using to test the rescheduler. I've cut out all cluster.yaml comments and I'm left with just this:

```
clusterName: k8s-dev-v1
externalDNSName: k8s-dev-v1.REDACTED
createRecordSet: true
hostedZoneId: REDACTED
keyName: REDACTED
region: eu-west-1
kmsKeyArn: "arn:aws:kms:eu-west-1:REDACTED"
controller:
 autoScalingGroup:
   minSize: 2
   maxSize: 3
   rollingUpdateMinInstancesInService: 1
 subnets:
   - name: ManagedPublicSubnet1
   - name: ManagedPublicSubnet2
   - name: ManagedPublicSubnet3
worker:
  nodePools:
    - name: nodepool1
      subnets:
        - name: ManagedPublicSubnet1
    - name: nodepool2
      subnets:
        - name: ManagedPublicSubnet2
    - name: nodepool3
      subnets:
        - name: ManagedPublicSubnet3
subnets:
  - name: ManagedPublicSubnet1
    availabilityZone: eu-west-1a
    instanceCIDR: "10.0.100.0/24"
  - name: ManagedPublicSubnet2
    availabilityZone: eu-west-1b
    instanceCIDR: "10.0.101.0/24"
  - name: ManagedPublicSubnet3
    availabilityZone: eu-west-1c
    instanceCIDR: "10.0.102.0/24"
addons:
  rescheduler:
    enabled: true
```

**Comment by mumoshu** [comment] 2017-04-03 23:19
Thanks. With the kube-aws binary built from 7e0f739053514fcfd47c2eb9da1c12efe099ef04, the output for me didn't contain the message:

```
$ ./kube-aws render stack
Success! Stack rendered to ./stack-templates.

Next steps:
1. (Optional) Validate your changes to cluster.yaml with "kube-aws validate"
2. (Optional) Further customize the cluster by modifying templates in ./stack-templates or cloud-configs in ./userdata.
3. (Optional) Add more authentication tokens in ./credentials/tokens.csv
4. Start the cluster with "kube-aws up".
```

**Comment by c-knowles** [comment] 2017-04-04 03:31
I realised this warning log is output from `validate` rather than `render stack`. I got the wrong one since I've wired our internal render command to always perform a validation after render (could be a good flag for us to have actually?).

I've updated to current master https://github.com/kubernetes-incubator/kube-aws/commit/1ccf196f4751416d2faa78bd847170531304828f and can not reproduce so either this is my user error or the issue is no longer present. Happy to close until I see it again.

**Comment by mumoshu** [comment] 2017-04-10 02:08
Thanks for the report. I'm closing this for now but please feel free to reopen once the issue gets reproduced again.

**Closed by mumoshu** 2017-04-10 02:08 UTC

**Comment by chris-david-taylor** [comment] 2017-05-25 21:09
Hi,  
I hope I'm not reopening a closed issue, but I'm seeing the same issue with version v0.9.6-rc.4 and v0.9.7-rc.2

"WARN: the worker node pool "nodepool1" is associated to a k8s API endpoint behind the DNS name "my domain.com" managed by YOU!"

My colleagues are seeing this also.  Anything useful I can do to help debug?

**Comment by jacohend** [comment] 2017-06-07 21:42
Also still seeing this issue while following the official kube-aws guide.

**Comment by mumoshu** [comment] 2017-06-07 21:58
@jacohend Hi, thanks for trying kube-aws!

To investigate further, could you provide me your kube-aws version and cluster.yaml?

**Comment by jacohend** [comment] 2017-06-07 22:27
Thanks @mumoshu

Kernel: Linux jacob-XPS-15 4.10.0-22-generic #24-Ubuntu SMP Mon May 22 17:43:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Version: kube-aws version v0.9.7-rc.2

```
clusterName: mya-staging

apiEndpoints:
  name: default

  dnsName: staging.trymya.io

  loadBalancer:

    createRecordSet: false
keyName: us-west-1-dev

region: us-west-1

availabilityZone: us-west-1a

kmsKeyArn: "redacted"


worker:
  nodePools:
    - # Name of this node pool. Must be unique among all the node pools in this cluster
      name: nodepool1
addons:

  clusterAutoscaler:
    enabled: false

  rescheduler:
    enabled: false```

**Comment by mumoshu** [comment] 2017-06-07 23:12
@jacohend Thanks for the reply 👍 

According to the contents of cluster.yaml you've provided, the message `WARN: the worker node pool "nodepool1" is associated to a k8s API endpoint behind the DNS name "staging.trymya.io" managed by YOU!` seems to tell the truth.

In short, you need to add the `--hosted-zone-id` flag when running `kube-aws init`, i.e. set `apiEndpoints[].loadBalancer.hostedZone.id` in cluster.yaml, so that kube-aws is able to provision a Route53 record set for you.
I guess [this part of kube-aws doc](https://github.com/kubernetes-incubator/kube-aws/blob/master/Documentation/kubernetes-on-aws-render.md#route53-host-record) would help.
